### ISSUE TITLE
warface news

### ISSUE THREAD

**Issue by ericzwicker** [seanwlk/wfbot#2]
hi seanwlk, 
my name is [OM]p0rt3r a Officer from OrbiaMortis. On our Discord we have a warface news channel and i try to implement the push news in an specific channel on our server. i heard it is possible with ure bot. pls tell me how.

thx for ure good work
 eric/ porter

**Comment by seanwlk** [comment]
I need the following information:
- Channel name
- Does the not have the right permissions in that channel? To send messages and Embeds?

**Comment by ericzwicker** [comment]
oh wow didnt see ure fast answer sry.
we successfull finished it yesterday and now we hope it works. 

thx again :)
greetings eric

**Comment by seanwlk** [comment]
What do you mean you hope it works? I didn't add the news push to your server, I'm still waiting for the info.

**Comment by ericzwicker** [comment]
we have done it with an rss feed and zapier.com. we are just at the beginning to modifying our discord and change a lot more in the next weeks. channel names and channel itselfs changed too and with zapier.com we can integrate twitch and youtube too.

**Comment by seanwlk** [comment]
Ok then I'll close this 👍
