### ISSUE TITLE
About wfbot

### ISSUE THREAD

**Issue by Mr-Ed-ZA** [seanwlk/wfbot#3]
Hey man sorry if this in the wrong place I'm new to everything here...

I got your wfbot and it is real nice but for the love of me i have no idea where i must do this next part 
(You can have the news pushed out to your server automatically on a specific channel if you request the feature to <@159015952346906624>) I am really a noob to this stuff so if you can tell me where to go or how to do it step by step it will be awesome...

**Comment by seanwlk** [comment]
That means you have to contact me to setup the news push. 
I need the server name and the channel name where you'd like the news. 

NOTE.
I don't configure this for servers with less than 30 users.

**Comment by Mr-Ed-ZA** [comment]
okay i guess i will come back later cause it is a new server and it is still growing...

Thanks for the replay...

**Comment by seanwlk** [comment]
Easier if you hit me up on discord @seanwlk#3004 if you are on the official discord you can contact me.
