### ISSUE TITLE
News

### ISSUE THREAD

**Issue by MatinArif** [seanwlk/wfbot#5]
Hi i have discord server and i want automatic news setup in it how can i get it ?

**Comment by seanwlk** [comment]
Current requirement is that your server must have at least 40 members. If it does, i need server name/ID and channel ID

**Comment by MatinArif** [comment]
Hi
Sir where do I find that information ?

**Comment by seanwlk** [comment]
@MatinArif you dont know your server name and channel name where you want the news? 

👀

**Comment by MatinArif** [comment]
**spetsnaz**
#news

**Comment by MatinArif** [comment]
https://discord.gg/KqEGx3

**Comment by seanwlk** [comment]
@MatinArif done
