### ISSUE TITLE
A lot of coding

### ISSUE THREAD

**Issue by chrisdiscordandmore** [seanwlk/wfbot#6]
Hi,
I am just wondering how you use the data(API from a user/stat) from jsonpath full_response": since it's not an array or anything
I have no trouble with the other data since it's nicely written in arrays. But in the last big chunk(full_response) I can't figure out how to separate the data from eachother. My Idea is Either to replace parts of the string to make an array or to make every new line an array (\n). 
How did u do it?

Looking forward to hearing from you.
Chris

**Comment by seanwlk** [comment]
Made a function that splits by \n and returns a dict instead of having to split text

**Comment by chrisdiscordandmore** [comment]
Thanks for the helpful insight.... it took me several hours of troubleshooting. Slowly i am beginning to hate javascript lol. But now it works so thanks again. Now i just have to find the data like, missions, stats and weapons
