### ISSUE TITLE
WFbot

### ISSUE THREAD

**Issue by Hoggiest** [seanwlk/wfbot#9]
Hello
I would like to ask if you could give me the code so that I can try to translate your bot into Russian

**Comment by seanwlk** [comment]
Not gonna happen. It's not like there is much English. It's just few words that you have to know.

**Comment by Hoggiest** [comment]
Simply in your bot are used English sites on Warface. I would like to try to optimize this for the Russian user

**Comment by seanwlk** [comment]
Do you mean the news automatic push? If so i have plans for the future to make it work for RU too  but have no time to develop it.
But anyway, as I said, I will not publish the source. It's an as is product.
